// <auto-generated />
using System;
using EVDealer.BE.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVDealer.BE.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016150213_AddPermissionAndRolePermissionTables")]
    partial class AddPermissionAndRolePermissionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdDocumentNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id_document_number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__CD65CB851DFCF011");

                    b.HasIndex(new[] { "IdDocumentNumber" }, "UQ__Customer__8D0A37D79075E7B9")
                        .IsUnique()
                        .HasFilter("[id_document_number] IS NOT NULL");

                    b.HasIndex(new[] { "Phone" }, "UQ__Customer__B43B145F955C8FF0")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Dealer", b =>
                {
                    b.Property<int>("DealerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dealer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DealerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("DealerId")
                        .HasName("PK__Dealer__019990C0196E5CEB");

                    b.ToTable("Dealer", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DemandForecast", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("forecast_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForecastId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("DealerId")
                        .HasColumnType("int")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("ForecastPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("forecast_period_end");

                    b.Property<DateOnly>("ForecastPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("forecast_period_start");

                    b.Property<int>("PredictedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("predicted_quantity");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("ForecastId")
                        .HasName("PK__DemandFo__9E57315448507800");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DemandForecast", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Distribution", b =>
                {
                    b.Property<int>("DistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dist_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistId"));

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("from_location");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int>("ToDealerId")
                        .HasColumnType("int")
                        .HasColumnName("to_dealer_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("DistId")
                        .HasName("PK__Distribu__FBDA893075D5E843");

                    b.HasIndex("ToDealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Distribution", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("location_type");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("InventoryId")
                        .HasName("PK__Inventor__B59ACC49D4996A94");

                    b.HasIndex("ConfigId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("ConfigId")
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderId", "VehicleId", "ConfigId")
                        .HasName("PK__OrderIte__B93AF42AF183E452");

                    b.HasIndex("ConfigId");

                    b.HasIndex("VehicleId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("method");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__ED1FC9EA068AA6C1");

                    b.HasIndex("OrderId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("DealerId")
                        .HasColumnType("int")
                        .HasColumnName("dealer_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("RequestId")
                        .HasName("PK__Purchase__18D3B90F9530E59F");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("PurchaseRequest", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Quotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quotation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuotationId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("QuotationId")
                        .HasName("PK__Quotatio__7841D7DBFFBDCCAE");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Quotation", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__760965CCA51E8EB9");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Role__783254B1C9D2BF80")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role_Permission");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.SalesOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("DealerId")
                        .HasColumnType("int")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<int?>("QuotationId")
                        .HasColumnType("int")
                        .HasColumnName("quotation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.HasKey("OrderId")
                        .HasName("PK__SalesOrd__4659622959728F2E");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealerId");

                    b.HasIndex(new[] { "QuotationId" }, "UQ__SalesOrd__7841D7DAF7943B60")
                        .IsUnique()
                        .HasFilter("[quotation_id] IS NOT NULL");

                    b.ToTable("SalesOrder", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.TestDrive", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("DealerId")
                        .HasColumnType("int")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback");

                    b.Property<DateTime>("ScheduleDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("schedule_datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("TestId")
                        .HasName("PK__TestDriv__F3FF1C027F59B627");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TestDrive", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("DealerId")
                        .HasColumnType("int")
                        .HasColumnName("dealer_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370FEE195867");

                    b.HasIndex("DealerId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__User__F3DBC57225A4DD70")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("brand");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicle__F2947BC1502DA419");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.VehicleConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int?>("BatteryKwh")
                        .HasColumnType("int")
                        .HasColumnName("battery_kwh");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<int?>("RangeKm")
                        .HasColumnType("int")
                        .HasColumnName("range_km");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("ConfigId")
                        .HasName("PK__VehicleC__4AD1BFF16B4B452D");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleConfig", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DemandForecast", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("DemandForecasts")
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_DemandForecast_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("DemandForecasts")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_DemandForecast_Vehicle");

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Distribution", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "ToDealer")
                        .WithMany("Distributions")
                        .HasForeignKey("ToDealerId")
                        .IsRequired()
                        .HasConstraintName("FK_Distribution_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Distributions")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Distribution_Vehicle");

                    b.Navigation("ToDealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Inventory", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany("Inventories")
                        .HasForeignKey("ConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Config");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Inventories")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.OrderItem", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany("OrderItems")
                        .HasForeignKey("ConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Config");

                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("OrderItems")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Order");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Payment", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_SalesOrder");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.PurchaseRequest", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("DealerId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseRequest_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseRequest_Vehicle");

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Quotation", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.User", "CreatedByUser")
                        .WithMany("Quotations")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Quotation_User");

                    b.HasOne("EVDealer.BE.DAL.Models.Customer", "Customer")
                        .WithMany("Quotations")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Quotation_Customer");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.RolePermission", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDealer.BE.DAL.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.SalesOrder", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.User", "ApprovedByNavigation")
                        .WithMany("SalesOrders")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_SalesOrder_Approver");

                    b.HasOne("EVDealer.BE.DAL.Models.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesOrder_Customer");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("DealerId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesOrder_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Quotation", "Quotation")
                        .WithOne("SalesOrder")
                        .HasForeignKey("EVDealer.BE.DAL.Models.SalesOrder", "QuotationId")
                        .HasConstraintName("FK_SalesOrder_Quotation");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("Dealer");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.TestDrive", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Customer", "Customer")
                        .WithMany("TestDrives")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_TestDrive_Customer");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("TestDrives")
                        .HasForeignKey("DealerId")
                        .IsRequired()
                        .HasConstraintName("FK_TestDrive_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("TestDrives")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_TestDrive_Vehicle");

                    b.Navigation("Customer");

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.User", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("Users")
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_User_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Dealer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.VehicleConfig", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleConfigs")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_VehicleConfig_Vehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Customer", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("SalesOrders");

                    b.Navigation("TestDrives");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Dealer", b =>
                {
                    b.Navigation("DemandForecasts");

                    b.Navigation("Distributions");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("SalesOrders");

                    b.Navigation("TestDrives");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Quotation", b =>
                {
                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.SalesOrder", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.User", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Vehicle", b =>
                {
                    b.Navigation("DemandForecasts");

                    b.Navigation("Distributions");

                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("TestDrives");

                    b.Navigation("VehicleConfigs");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.VehicleConfig", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
