// <auto-generated />
using System;
using EVDealer.BE.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EVDealer.BE.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126175803_AddEmailToCustomerr")]
    partial class AddEmailToCustomerr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("contract_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContractId"));

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("contract_date");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("terms");

                    b.HasKey("ContractId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdDocumentNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_document_number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__CD65CB851DFCF011");

                    b.HasIndex(new[] { "IdDocumentNumber" }, "UQ__Customer__8D0A37D79075E7B9")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ__Customer__B43B145F955C8FF0")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Dealer", b =>
                {
                    b.Property<int>("DealerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DealerId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("SafetyStockLevel")
                        .HasColumnType("integer");

                    b.HasKey("DealerId")
                        .HasName("PK__Dealer__019990C0196E5CEB");

                    b.HasIndex("RegionId");

                    b.ToTable("Dealer", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DealerContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("contract_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContractId"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Terms")
                        .HasColumnType("text")
                        .HasColumnName("terms");

                    b.HasKey("ContractId");

                    b.HasIndex("DealerId");

                    b.ToTable("DealerContract");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DealerInventory", b =>
                {
                    b.Property<int>("DealerInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dealer_inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DealerInventoryId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<int?>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<DateTime?>("LastRestockDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_restock_date");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("DealerInventoryId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DealerInventory", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DealerTarget", b =>
                {
                    b.Property<int>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TargetId"));

                    b.Property<decimal?>("ActualSales")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("actual_sales");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<decimal>("SalesTarget")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("sales_target");

                    b.HasKey("TargetId");

                    b.HasIndex("DealerId");

                    b.ToTable("DealerTarget");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Debt", b =>
                {
                    b.Property<int>("DebtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("debt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DebtId"));

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount_due");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("DebtId");

                    b.HasIndex("DealerId");

                    b.ToTable("Debt");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("delivery_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryId"));

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_date");

                    b.Property<string>("CarrierInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("carrier_info");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tracking_no");

                    b.HasKey("DeliveryId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Delivery", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DemandForecast", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("forecast_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForecastId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("ForecastPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("forecast_period_end");

                    b.Property<DateOnly>("ForecastPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("forecast_period_start");

                    b.Property<int>("PredictedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("predicted_quantity");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("ForecastId")
                        .HasName("PK__DemandFo__9E57315448507800");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DemandForecast", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Distribution", b =>
                {
                    b.Property<int>("DistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistId"));

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date");

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeliveredBy")
                        .HasColumnType("integer")
                        .HasColumnName("delivered_by");

                    b.Property<int?>("Dispatcher")
                        .HasColumnType("integer")
                        .HasColumnName("dispatcher");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_location");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("ScheduledBy")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_by");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int>("ToDealerId")
                        .HasColumnType("integer")
                        .HasColumnName("to_dealer_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("DistId")
                        .HasName("PK__Distribu__FBDA893075D5E843");

                    b.HasIndex("ConfigId");

                    b.HasIndex("ToDealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Distribution", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DistributionSuggestion", b =>
                {
                    b.Property<int>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SuggestionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentInventory")
                        .HasColumnType("integer");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<int>("ForecastedDemand")
                        .HasColumnType("integer");

                    b.Property<int>("SafetyStock")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SuggestedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("SuggestionId");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DistributionSuggestions");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("location_type");

                    b.Property<int>("QtyOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("qty_on_hand");

                    b.Property<int>("QtyOnHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("qty_on_hold");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("InventoryId")
                        .HasName("PK__Inventor__B59ACC49D4996A94");

                    b.HasIndex("ConfigId");

                    b.HasIndex("LocationId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("LocationType", "LocationId", "VehicleId", "ConfigId")
                        .IsUnique()
                        .HasDatabaseName("idx_inventory_location_vehicle_config");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderId", "VehicleId", "ConfigId")
                        .HasName("PK__OrderIte__B93AF42AF183E452");

                    b.HasIndex("ConfigId");

                    b.HasIndex("VehicleId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.OrderPromotion", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "PromotionId");

                    b.HasIndex("PromotionId");

                    b.ToTable("OrderPromotion", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__ED1FC9EA068AA6C1");

                    b.HasIndex("OrderId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PermissionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PermissionName");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("promo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PromotionId"));

                    b.Property<bool?>("Combinable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("combinable");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("discount_value");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<string>("Source")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("EVM")
                        .HasColumnName("source");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.PromotionPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("policy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("Conditions")
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discount_percent");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("PolicyId");

                    b.HasIndex("DealerId");

                    b.ToTable("PromotionPolicies");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("notes");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("RemainingQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remaining_qty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("RequestId")
                        .HasName("PK__Purchase__18D3B90F9530E59F");

                    b.HasIndex("ConfigId");

                    b.HasIndex("DealerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("VehicleId");

                    b.ToTable("PurchaseRequest", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Quotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quotation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuotationId"));

                    b.Property<int?>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<decimal?>("DownPaymentEst")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("down_payment_est");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OnroadPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("onroad_price");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAfter")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_after");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal?>("TotalBefore")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_before");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_discount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("QuotationId")
                        .HasName("PK__Quotatio__7841D7DBFFBDCCAE");

                    b.HasIndex("ConfigId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Quotation", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.QuotationItem", b =>
                {
                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("quotation_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("QuotationId", "VehicleId", "ConfigId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("VehicleId");

                    b.ToTable("QuotationItem", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.QuotationPromotion", b =>
                {
                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("quotation_id")
                        .HasColumnOrder(0);

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer")
                        .HasColumnName("promo_id")
                        .HasColumnOrder(1);

                    b.HasKey("QuotationId", "PromotionId");

                    b.HasIndex("PromotionId");

                    b.ToTable("QuotationPromotion", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__760965CCA51E8EB9");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Role__783254B1C9D2BF80")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role_Permission", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.SalesOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("ApprovalNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_note");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<decimal?>("OrderTotalAfter")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("order_total_after");

                    b.Property<decimal?>("OrderTotalBefore")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("order_total_before");

                    b.Property<decimal?>("OrderTotalDiscount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("order_total_discount");

                    b.Property<int?>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("quotation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.HasKey("OrderId")
                        .HasName("PK__SalesOrd__4659622959728F2E");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealerId");

                    b.HasIndex(new[] { "QuotationId" }, "UQ__SalesOrd__7841D7DAF7943B60")
                        .IsUnique();

                    b.ToTable("SalesOrder", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.StockRequest", b =>
                {
                    b.Property<int>("StockRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stock_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockRequestId"));

                    b.Property<int?>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Normal")
                        .HasColumnName("priority");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("processed_by_user_id");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_date");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("request_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("StockRequestId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("DealerId");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("StockRequest", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.TestDrive", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<DateTime>("ScheduleDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("schedule_datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("TestId")
                        .HasName("PK__TestDriv__F3FF1C027F59B627");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TestDrive", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int?>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370FEE195867");

                    b.HasIndex("DealerId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_User_Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ__User__F3DBC57225A4DD70")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicle__F2947BC1502DA419");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.VehicleConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<int?>("BatteryKwh")
                        .HasColumnType("integer")
                        .HasColumnName("battery_kwh");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<int?>("RangeKm")
                        .HasColumnType("integer")
                        .HasColumnName("range_km");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("ConfigId")
                        .HasName("PK__VehicleC__4AD1BFF16B4B452D");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleConfig", (string)null);
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.WholesalePrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("price_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceId"));

                    b.Property<int?>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("PriceId");

                    b.HasIndex("DealerId");

                    b.HasIndex("ProductId");

                    b.ToTable("WholesalePrices");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Contract", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithOne("Contract")
                        .HasForeignKey("EVDealer.BE.DAL.Models.Contract", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Contract_SalesOrder");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Dealer", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Region", "Region")
                        .WithMany("Dealers")
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DealerContract", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DealerInventory", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DealerInventory_VehicleConfig");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DealerInventory_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DealerInventory_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DealerTarget", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Debt", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Delivery", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("EVDealer.BE.DAL.Models.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Delivery_SalesOrder");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DemandForecast", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("DemandForecasts")
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_DemandForecast_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("DemandForecasts")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_DemandForecast_Vehicle");

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Distribution", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany("Distributions")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "ToDealer")
                        .WithMany("Distributions")
                        .HasForeignKey("ToDealerId")
                        .IsRequired()
                        .HasConstraintName("FK_Distribution_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Distributions")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Distribution_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("ToDealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.DistributionSuggestion", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Inventory", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany("Inventories")
                        .HasForeignKey("ConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Config");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Inventories")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Location");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.OrderItem", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany("OrderItems")
                        .HasForeignKey("ConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Config");

                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("OrderItems")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Order");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.OrderPromotion", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderPromotion_Order");

                    b.HasOne("EVDealer.BE.DAL.Models.Promotion", "Promotion")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderPromotion_Promotion");

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Payment", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_SalesOrder");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.PromotionPolicy", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.PurchaseRequest", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("ConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseRequest_Config");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("DealerId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseRequest_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.SalesOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_PurchaseRequest_Order");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseRequest_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Dealer");

                    b.Navigation("Order");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Quotation", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .HasConstraintName("FK_Quotation_Config");

                    b.HasOne("EVDealer.BE.DAL.Models.User", "CreatedByUser")
                        .WithMany("Quotations")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Quotation_User");

                    b.HasOne("EVDealer.BE.DAL.Models.Customer", "Customer")
                        .WithMany("Quotations")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Quotation_Customer");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_Quotation_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_Quotation_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.QuotationItem", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany("QuotationItems")
                        .HasForeignKey("ConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_QuotationItem_Config");

                    b.HasOne("EVDealer.BE.DAL.Models.Quotation", "Quotation")
                        .WithMany("QuotationItems")
                        .HasForeignKey("QuotationId")
                        .IsRequired()
                        .HasConstraintName("FK_QuotationItem_Quotation");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("QuotationItems")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_QuotationItem_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Quotation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.QuotationPromotion", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Promotion", "Promotion")
                        .WithMany("QuotationPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuotationPromotion_Promotion");

                    b.HasOne("EVDealer.BE.DAL.Models.Quotation", "Quotation")
                        .WithMany("QuotationPromotions")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuotationPromotion_Quotation");

                    b.Navigation("Promotion");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.RolePermission", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDealer.BE.DAL.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.SalesOrder", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.User", "ApprovedByNavigation")
                        .WithMany("SalesOrders")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_SalesOrder_Approver");

                    b.HasOne("EVDealer.BE.DAL.Models.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesOrder_Customer");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("DealerId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesOrder_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Quotation", "Quotation")
                        .WithOne("SalesOrder")
                        .HasForeignKey("EVDealer.BE.DAL.Models.SalesOrder", "QuotationId")
                        .HasConstraintName("FK_SalesOrder_Quotation");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("Dealer");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.StockRequest", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.VehicleConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_StockRequest_VehicleConfig");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockRequest_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.User", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_StockRequest_ProcessedByUser");

                    b.HasOne("EVDealer.BE.DAL.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockRequest_RequestedByUser");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockRequest_Vehicle");

                    b.Navigation("Config");

                    b.Navigation("Dealer");

                    b.Navigation("ProcessedBy");

                    b.Navigation("RequestedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.TestDrive", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Customer", "Customer")
                        .WithMany("TestDrives")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_TestDrive_Customer");

                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("TestDrives")
                        .HasForeignKey("DealerId")
                        .IsRequired()
                        .HasConstraintName("FK_TestDrive_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("TestDrives")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_TestDrive_Vehicle");

                    b.Navigation("Customer");

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.User", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany("Users")
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_User_Dealer");

                    b.HasOne("EVDealer.BE.DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Dealer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.VehicleConfig", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleConfigs")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_VehicleConfig_Vehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.WholesalePrice", b =>
                {
                    b.HasOne("EVDealer.BE.DAL.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId");

                    b.HasOne("EVDealer.BE.DAL.Models.Vehicle", "Product")
                        .WithMany("WholesalePrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Customer", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("SalesOrders");

                    b.Navigation("TestDrives");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Dealer", b =>
                {
                    b.Navigation("DemandForecasts");

                    b.Navigation("Distributions");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("SalesOrders");

                    b.Navigation("TestDrives");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Promotion", b =>
                {
                    b.Navigation("OrderPromotions");

                    b.Navigation("QuotationPromotions");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Quotation", b =>
                {
                    b.Navigation("QuotationItems");

                    b.Navigation("QuotationPromotions");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Region", b =>
                {
                    b.Navigation("Dealers");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.SalesOrder", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Delivery");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderPromotions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.User", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.Vehicle", b =>
                {
                    b.Navigation("DemandForecasts");

                    b.Navigation("Distributions");

                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("QuotationItems");

                    b.Navigation("TestDrives");

                    b.Navigation("VehicleConfigs");

                    b.Navigation("WholesalePrices");
                });

            modelBuilder.Entity("EVDealer.BE.DAL.Models.VehicleConfig", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("QuotationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
